services:
  - type: web
    name: vetpet-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    branch: main
    rootDir: frontend
    port: 80
